Revert "Drop buildroot rpmbuild parameter"
This reverts commit e9427819ad002eafd990f3220c5a5a11ba99f6d5.

buildroot need to be set so package which use $RPM_BUILD_ROOT do not fail.
E.g.: aaa_base

+ cd aaa_base
+ make DESTDIR=/home/abuild/rpmbuild/BUILDROOT/aaa_base-12.1-1.2.i386 install
cp -a files/* /home/abuild/rpmbuild/BUILDROOT/aaa_base-12.1-1.2.i386/
cp: target `/home/abuild/rpmbuild/BUILDROOT/aaa_base-12.1-1.2.i386/' is not a directory
make: *** [install] Error 1
error: Bad exit status from /opt/b1/armv7l-b1-linux-gnueabi/sys-root/var/tmp/rpm-tmp.pinwZT (%install)